#version: "3.9"
services:
  banco:
    image: postgres:11
    container_name: postgres
    ports:
      - 5432:5432
    networks:
      - teste-bridge 
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - ./bancovolume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 30s
      timeout: 30s
      retries: 5

  node:
    build:
      context: .
      args:
        PORTA: 8080
    container_name: node_teste
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - teste-bridge 
    command: "npm run dev"
    depends_on:
      banco:
        condition: service_healthy
  

      
  swagger:
    image: docker.swagger.io/swaggerapi/swagger-ui
    container_name: swagger_fiap_loja
    ports:
      - 8081:8080
    networks:
      - teste-bridge 
    environment:
      API_URL: http://localhost:8081/swagger.yml
      BASE_URL: /swagger
      SWAGGER_JSON: /swagger/swagger.yml
    volumes:
      - ./swagger:/swagger
    depends_on:
      - node
      

networks:
  teste-bridge:
    driver: bridge